### ISSUE TITLE
Permission denied when cloning manually 

### ISSUE THREAD

**Issue by bikegirl** [rimraf/k#96]
I have mac0S Catalina 10.15.4
running a zsh shell

Followed the exact steps to installing manually.  And I get a cloning the repo permission denied error...
![image](https://user-images.githubusercontent.com/31639520/83912577-b4fef580-a733-11ea-986a-45aaf64c4c28.png)

**Comment by Swivelgames** [comment]
Hey @bikegirl 

It looks like you're attempting to clone via SSH. In order to do this, you'll need to [add a public SSH key to your Github Account](https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account).

Alternatively, you can just clone via HTTPS, which shouldn't require you to setup SSH. In this case, click the "`Use HTTPS`" link in the top right corner, and then copy the new URL.

![image](https://user-images.githubusercontent.com/1456302/84183750-feac5080-aa51-11ea-969a-1e8d67a92d15.png)

**Comment by Swivelgames** [comment]
However, I would highly recommend getting a plugin manager for ZSH instead of installing it manually. I personally use [`Oh-My-Zsh`](https://github.com/ohmyzsh/ohmyzsh), but many others use [`zplug`](https://github.com/zplug/zplug), [`zgen`](https://github.com/tarjoilija/zgen), or [`Antigen`](https://github.com/zsh-users/antigen). Those make installing this so much easier! :)

**Comment by bikegirl** [comment]
Thanks for the response, I ended up trying Oh-My-Zsh, and I love it so
far!!!  Thanks for the rec.



*Becca*

| MS Computer Science
https://greedykruskal.me
Book me on Calendly! <https://calendly.com/greedykruskal>
NSF GRFP Fellow

**Comment by Swivelgames** [comment]
Great! I'm glad you were able to get `Oh-My-Zsh` working. I love it too!

If this is solved, go ahead and Close the issue :smile:

**Comment by bikegirl** [comment]
Done!



*Becca*

| MS Computer Science
https://greedykruskal.me
Book me on Calendly! <https://calendly.com/greedykruskal>
NSF GRFP Fellow
